model: PN

# 注: 所有路径都需以项目为根目录写起.

# 路径相关参数
data_params:

  # 训练、开发、测试数据路径
  path_train: ./data/train.json
  path_dev:
  path_test: ./data/test.json
  path_test_result: ./data/test.output  # default is path_test+'.output'

  # 定义特征列数, 以及特征别名
  feature_cols: [0]
  feature_names: [word]  # feature alias

  # alphabet参数及存放路径
  alphabet_params:
    min_counts: [0]
    path: ./data/alphabet/  # 特征字典存放根目录

  # 预训练特征向量路径, 按feature_names顺序设置, 没有预训练向量则设为null
  path_pretrain:
    - E:\\py workspace\\sgns.renmin.bigram-char\\sgns.renmin.bigram-char
    - null
    - null

  # 模型存放路径
  path_model: ./data/model_save


# 模型参数
model_params:

  # embedding parameters, 若提供了path_pretrain参数, 则以预训练维度为准
  embed_sizes: [300]
  # 是否更新feature embedding table
  require_grads: [true]

  # rnn parameters
  rnn_type: lstm  # `rnn`, `lstm` or `gru`
  rnn_layers: 1
  rnn_units: 200
  bi_flag: true

  # cnn parameters
  conv_filter_sizes: 3
  conv_filter_nums: 30

  # pointer network
  weight_size: 512


  # train parameters
  dev_size: 0.1  # 若没有`path_dev`参数, 则根据该值划分训练集
  batch_size: 100
  dropout_rate: 0.5
  learning_rate: 0.015
  optimizer: sgd  # sgd, adam, adadelta, ...
  l2_rate: 1.0e-8
  lr_decay: 0.05  # only for sgd optimizer
  momentum: 0.
  clip: 5  # TODO grad clip
  max_patience: 20
  nb_epoch: 1000
  average_batch: false

  use_cuda: true
  deterministic: false

word_norm: true  # word normalization
max_len_limit: 250  # batch的长度上限(非max_len)
all_in_memory: true  # 数据全部加载到内存
